CUDA_VISIBLE_DEVICES=1 python /scratch/users/rbhalerao/CPH200A_project2/scripts/main.py \
    --model_name resnet_adapt \
    --dataset_name nlst \
    --train True \
    --pretraining True \
    --batch_size 2 \
    --class_balance True \
    --num_workers 0 \
    --project_name "cornerstone_project_2" \
    --wandb_entity "cph29" \
    --depth_handling "max_pool" 
